### ISSUE TITLE
Crash on first startup

### ISSUE THREAD

**Issue by timothymctim** [nanu-c/textsecure-qml#16]
### Description
App crashes on first start.

### Steps to Reproduce

1. Download version 0.3.18 from the OpenStore
2. Launch the app by clicking on the icon on the home screen

**Expected behavior:** [What you expect to happen]
Registration form.

**Actual behavior:** [What actually happens]
Crash

**Reproduces how often:** [What percentage of the time does it reproduce?]
Always

### Additional Information
Log file information from `application-click-textsecure.nanuc_textsecure_0.3.18.log`
```
[36mINFO[0m[0000] Starting TextSecure                          
[36mINFO[0m[0000] Starting Signal for Ubuntu version 0.3.18    
2018/02/27 20:05:18 LogFile: /home/phablet/.cache/upstart/application-click-textsecure.nanuc_textsecure_0.3.18.log
[36mINFO[0m[0000] Setup completed                              
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
[36mINFO[0m[0000] open /home/phablet/.config/textsecure.nanuc/settings.yml: no such file or directory 
2018/02/27 20:05:24 .:0: could not open containers config file  "/home/phablet/.local/share/libertine/ContainersConfig.json"
2018/02/27 20:05:24 Page.qml:158: TelegramPage_QMLTYPE_45(0x16b6bd8): In Ubuntu.Components 1.3, the use of Page.title, Page.flickable and Page.head is deprecated. Use Page.header and the PageHeader component instead.
2018/02/27 20:05:24 TelegramPage.qml:98: file:////opt/click.ubuntu.com/textsecure.nanuc/0.3.18/qml/phoneui/components/TelegramPage.qml:98:5: QML ActivityIndicator: file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/Themes/Ambiance/1.3/ActivityIndicatorStyle.qml:24 Invalid property assignment: "implicitHeight" is a read-only property

[37mDEBU[0m[2018/02/27 20:05:24] Opening Dialog: getPhoneNumber               
2018/02/27 20:05:24 Page.qml:158: TelegramPage_QMLTYPE_45(0x171d800): In Ubuntu.Components 1.3, the use of Page.title, Page.flickable and Page.head is deprecated. Use Page.header and the PageHeader component instead.
2018/02/27 20:05:24 TextField.qml:905: file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/1.2/TextField.qml:905:5: QML AbstractButton: Mixing of Ubuntu.Components module versions 1.2 and 1.3 detected!
2018/02/27 20:05:24 TelegramPage.qml:98: file:////opt/click.ubuntu.com/textsecure.nanuc/0.3.18/qml/phoneui/components/TelegramPage.qml:98:5: QML ActivityIndicator: file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/Themes/Ambiance/1.3/ActivityIndicatorStyle.qml:24 Invalid property assignment: "implicitHeight" is a read-only property

panic: cannot find descendant with objectName == "signInPage"

goroutine 21 [running]:
panic(0x625e78, 0x93e42108)
	/usr/local/go/src/runtime/panic.go:464 +0x330
github.com/nanu-c/qml-go.(*Common).ObjectByName(0x93e2d080, 0x736580, 0xa, 0x0, 0x0)
	/home/developer/gopath/src/github.com/nanu-c/qml-go/qmlcommon.go:305 +0x230
github.com/nanu-c/textsecure-qml/app/ui.GetTextFromDialog(0x73ef50, 0xe, 0x736580, 0xa, 0x7405c0, 0xd, 0x0, 0x0)
	/home/developer/gopath/src/github.com/nanu-c/textsecure-qml/app/ui/dialogs.go:12 +0xfc
github.com/nanu-c/textsecure-qml/app/ui.GetPhoneNumber(0x0, 0x0)
	/home/developer/gopath/src/github.com/nanu-c/textsecure-qml/app/ui/dialogs.go:26 +0x50
github.com/morph027/textsecure.registerDevice(0x0, 0x0)
	/home/developer/gopath/src/github.com/morph027/textsecure/textsecure.go:329 +0x44
github.com/morph027/textsecure.Setup(0x93e5e390, 0x0, 0x0)
	/home/developer/gopath/src/github.com/morph027/textsecure/textsecure.go:305 +0x228
github.com/nanu-c/textsecure-qml/app/worker.RunBackend()
	/home/developer/gopath/src/github.com/nanu-c/textsecure-qml/app/worker/textsecureapi.go:91 +0x1dc
created by main.RunUI
	/home/nanu/src/go/src/github.com/nanu-c/textsecure-qml/main.go:43 +0x18c
```
#### Versions
0.3.18

Please provide the Version as written in `Settings->Advanced-> Submit Debug Log`
_(unable to follow the instructions as above)_

#### Device
BQ Aquaris E4.5 Ubuntu Edition

**Comment by timothymctim** [comment]
I tried to skip registration by copying the contents of `/home/phablet/.local/share/textsecure.jani/.storage` to `/home/phablet/.local/share/textsecure.nanuc/.storage`. However, by doing so, I wasn’t able to send any messages.

**Comment by timothymctim** [comment]
Oeh, nice. I’ve figured by reading the source that the following will do:
```
tel: "[my cell number]"
server: https://textsecure-service.whispersystems.org:443
rootCA: ""
proxy: ""
verificationType: sms
storageDir: /home/phablet/.local/share/textsecure.nanuc/.storage
unencryptedStorage: true
storagePassword: ""
loglevel: debug
userAgent: TextSecure 0.3.18 for Ubuntu Phone
alwaysTrustPeerID: true
```

It worked indeed! Thanks again for squatting some of the bugs in the `jani` version! Great work!

Although I’ve now successfully worked around this bug, you might want to fix it for other new users of your app as well :)

**Comment by nanu-c** [comment]
The Problem is 
`panic: cannot find descendant with objectName == "signInPage"`
In the corresponding line the gofunction searches for an qml objectname, which exists and isn't found. The only thing i changed in the main.qml is updating the qtquick and the ubuntu.components version.

```
import QtQuick 2.4
import Ubuntu.Components 1.3
```

So for me this is a bug in the go<->qml bridge

**Comment by nanu-c** [comment]
The sync devices qr-code scan page needs 
```
import QtQuick 2.4
import Ubuntu.Components 1.3
```
so I can disable that and it's working again

**Comment by timothymctim** [comment]
I cannot comment on whether that would indeed resolve the issue, or if it hasn’t any side effect, but great if you found the bug that quickly!

**Comment by rubencarneiro** [comment]
Same here. crash

**Comment by nanu-c** [comment]
This should be now resolved!!!
