### ISSUE TITLE
App crashes on Nexus 5

### ISSUE THREAD

**Issue by Nativeworld** [nanu-c/textsecure-qml#5]
Hi, thanks for your work.
The app works fine on BQ E5.
The app crashes on Nexus 5 when i try to open a contact to write e message.
The keyboard starts, but the contact list freeze and the app crashes.

**Comment by Flohack74** [comment]
I am on FP2 and cant open the App anymore. Think that this is not device-specific, but a certain condition in the persistent data which might indicate that it has been corrupted somehow, or a protocol change on the server side. Fact is that it was never working flawlessly, and crashed a lot, mostly when either opening it or opening a dialog. But this was not happening all the time, as it does currently.

**Comment by nanu-c** [comment]
May you provide me a link to your debug log under

`Settings->Advanced->Submit Debug Log`

**Comment by Flohack74** [comment]
See https://gist.github.com/anonymous/fc72130b0eb2574236fd211380ea298d - Currently it happens every time when I want to open a chat, the app crashes. Note that new messages are being marked as read though. Its annyoing since now my peers think I got the messages, but I cannot reply to them.

**Comment by nanu-c** [comment]
```
time="2017/12/28 14:03:36" level=info msg="The phone number supplied was empty."
time="2017/12/28 14:03:36" level=info msg="Parsing VCard 204 illegal base64 data at input byte 5008\n"
```

**Comment by nanu-c** [comment]
```
2017/12/31 21:02:11 GetAvatarImage
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x2 addr=0x17b2de8 pc=0x17b2de8]

runtime stack:
runtime.throw(0x741638, 0x2a)
	/usr/local/go/src/runtime/panic.go:530 +0x78
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x44

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x4eed3c, 0x94275f14, 0x0)
	/usr/local/go/src/runtime/cgocall.go:123 +0x11c fp=0x94275efc sp=0x94275ee4
github.com/amlwwalker/qml._Cfunc_applicationExec()
	??:0 +0x34 fp=0x94275f10 sp=0x94275efc
github.com/amlwwalker/qml.Run(0x794558, 0x0, 0x0)
	/home/developer/gopath/src/github.com/amlwwalker/qml/bridge.go:64 +0x14c fp=0x94275f3c sp=0x94275f10
main.main()
	/home/developer/main.go:51 +0xc4 fp=0x94275f94 sp=0x94275f3c
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b4 fp=0x94275fbc sp=0x94275f94
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:990 +0x4 fp=0x94275fbc sp=0x94275fbc

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:990 +0x4

goroutine 5 [chan receive]:
database/sql.(*DB).connectionOpener(0x93e7cfc0)
	/usr/local/go/src/database/sql/sql.go:727 +0x38
created by database/sql.Open
	/usr/local/go/src/database/sql/sql.go:493 +0x2a4

goroutine 50 [sleep]:
time.Sleep(0x7e11d600, 0x3)
	/usr/local/go/src/runtime/time.go:59 +0x104
github.com/janimo/textsecure.(*wsConn).keepAlive(0x940aabf0)
	/home/developer/gopath/src/github.com/janimo/textsecure/websocket.go:149 +0x130
created by github.com/janimo/textsecure.StartListening
	/home/developer/gopath/src/github.com/janimo/textsecure/websocket.go:182 +0x134

goroutine 34 [IO wait]:
net.runtime_pollWait(0x7cf59520, 0x72, 0x93ee4000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x941de038, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x941de038, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x941de000, 0x93ee4000, 0x800, 0x800, 0x0, 0x833ba030, 0x93d5a068)
	/usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x93efa000, 0x93ee4000, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x94144100, 0x833bea30, 0x93efa000, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xc8
crypto/tls.(*Conn).readRecord(0x93db4000, 0x794917, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x240
crypto/tls.(*Conn).Read(0x93db4000, 0x9413b000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x13c
bufio.(*Reader).fill(0x93eeab10)
	/usr/local/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).ReadByte(0x93eeab10, 0x93f10600, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:229 +0x8c
golang.org/x/net/websocket.hybiFrameReaderFactory.NewFrameReader(0x93eeab10, 0x833bf6f0, 0x93f10600, 0x0, 0x0)
	/home/developer/gopath/src/golang.org/x/net/websocket/hybi.go:123 +0xb0
golang.org/x/net/websocket.Codec.Receive(0x7944dc, 0x7944e0, 0x93d666e0, 0x5d22a8, 0x940aacd0, 0x0, 0x0)
	/home/developer/gopath/src/golang.org/x/net/websocket/websocket.go:338 +0x164
github.com/janimo/textsecure.(*wsConn).receive(0x940aabf0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/developer/gopath/src/github.com/janimo/textsecure/websocket.go:107 +0x7c
github.com/janimo/textsecure.StartListening(0x0, 0x0)
	/home/developer/gopath/src/github.com/janimo/textsecure/websocket.go:185 +0x144
github.com/nanu-c/textsecure-qml/worker.RunBackend()
	/home/developer/gopath/src/github.com/nanu-c/textsecure-qml/worker/textsecureapi.go:95 +0x464
created by main.RunUI
	/home/developer/main.go:43 +0x16c

goroutine 18 [sleep]:
time.Sleep(0xf8475800, 0xd)
	/usr/local/go/src/runtime/time.go:59 +0x104
github.com/nanu-c/textsecure-qml/store.UpdateTimestamps()
	/home/developer/gopath/src/github.com/nanu-c/textsecure-qml/store/session.go:119 +0x24
created by github.com/nanu-c/textsecure-qml/ui.InitModels
	/home/developer/gopath/src/github.com/nanu-c/textsecure-qml/ui/gui.go:50 +0x1d4

goroutine 13 [semacquire]:
sync.runtime_Semacquire(0x93ef8274)
	/usr/local/go/src/runtime/sema.go:47 +0x24
sync.(*Mutex).Lock(0x93ef8270)
	/usr/local/go/src/sync/mutex.go:83 +0x1fc
github.com/amlwwalker/qml.(*Window).Wait(0x93efa018)
	/home/developer/gopath/src/github.com/amlwwalker/qml/qml.go:919 +0x94
main.RunUI(0x0, 0x0)
	/home/developer/main.go:44 +0x17c
github.com/amlwwalker/qml.Run.func1(0x93ea9900, 0x794558)
	/home/developer/gopath/src/github.com/amlwwalker/qml/bridge.go:61 +0x28
created by github.com/amlwwalker/qml.Run
	/home/developer/gopath/src/github.com/amlwwalker/qml/bridge.go:63 +0x148

goroutine 15 [IO wait]:
net.runtime_pollWait(0x7cf59610, 0x72, 0x93de9800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0x93ea9af8, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x34
net.(*pollDesc).WaitRead(0x93ea9af8, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x30
net.(*netFD).Read(0x93ea9ac0, 0x93de9800, 0x400, 0x400, 0x0, 0x833ba030, 0x93d5a068)
	/usr/local/go/src/net/fd_unix.go:250 +0x1c4
net.(*conn).Read(0x93edb208, 0x93de9800, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xc8
crypto/tls.(*block).readFromUntil(0x93edd980, 0x833bea30, 0x93edb208, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xc8
crypto/tls.(*Conn).readRecord(0x9418a000, 0x794917, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x240
crypto/tls.(*Conn).Read(0x9418a000, 0x9419c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x13c
net/http.noteEOFReader.Read(0x833becf8, 0x9418a000, 0x93f183b4, 0x9419c000, 0x1000, 0x1000, 0x93d4a0d0, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x5c
net/http.(*noteEOFReader).Read(0x94190180, 0x9419c000, 0x1000, 0x1000, 0x93d80e14, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0x93eef170)
	/usr/local/go/src/bufio/bufio.go:97 +0x1c4
bufio.(*Reader).Peek(0x93eef170, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0x93f18380)
	/usr/local/go/src/net/http/transport.go:1069 +0x158
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0xdc0

goroutine 16 [select]:
net/http.(*persistConn).writeLoop(0x93f18380)
	/usr/local/go/src/net/http/transport.go:1273 +0x344
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0xddc

goroutine 66 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_arm.s:990 +0x4
```

**Comment by nanu-c** [comment]
Is this still happening?

**Comment by Bf88** [comment]
It's not crashing anymore on my nexus 5

**Comment by nanu-c** [comment]
Thanks, so I close this
