### ISSUE TITLE
Application crashes when started

### ISSUE THREAD

**Issue by Flaburgan** [nanu-c/textsecure-qml#67]
Since I wrote a message (not the first one), the application crashes at launch.

Here is the log:
```
ESC[36mINFOESC[0m[0000] Starting TextSecure                          
ESC[36mINFOESC[0m[0000] Starting Signal for Ubuntu version 0.4.1     
2019/07/31 23:17:42 LogFile: /home/phablet/.cache/upstart/application-click-textsecure.nanuc_textsecure_0.4.1.log
ESC[36mINFOESC[0m[0000] Setup completed                              
Loading module: 'libubuntu_application_api_touch_mirclient.so.3.0.0'
2019/07/31 23:17:44 .:0: error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.249\" (uid=32011 pid=32533 comm=\"textsecure \") interface=\"com.canonical.libertine.Service.Operations\" member=\"list\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4114 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
2019/07/31 23:17:44 .:0: error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.249\" (uid=32011 pid=32533 comm=\"textsecure \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"running\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4114 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
2019/07/31 23:17:44 .:0: lastError - no arguments?
2019/07/31 23:17:44 .:0: error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.249\" (uid=32011 pid=32533 comm=\"textsecure \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"last_error\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4114 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
2019/07/31 23:17:44 .:0: lastError - no arguments?
2019/07/31 23:17:44 .:0: error calling result "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.249\" (uid=32011 pid=32533 comm=\"textsecure \") interface=\"com.canonical.libertine.Service.OperationsMonitor\" member=\"result\" error name=\"(unset)\" requested_reply=\"0\" destination=\"com.canonical.libertine.Service\" (uid=32011 pid=4114 comm=\"/usr/bin/python3 /usr/bin/libertined \")"
2019/07/31 23:17:44 .:0: lastError - no arguments?
2019/07/31 23:17:45 OptionSelector.qml:330: file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/1.3/OptionSelector.qml:330:13: QML ListView: Binding loop detected for property "itemHeight"
ESC[37mDEBUESC[0m[0002] New Storage                                  
ESC[37mDEBUESC[0m[0002] NewDataStore                                 
ESC[37mDEBUESC[0m[0002] NewDataStore finished                        
2019/07/31 23:17:45 Loading Messages
ESC[36mINFOESC[0m[0003] Db setup finished                            
library "/vendor/lib/egl/libGLESv2S3D_adreno.so" not found
ESC[37mDEBUESC[0m[0003] Run Backend                                  
ESC[37mDEBUESC[0m[0003] Start Session after Decryption               
ESC[37mDEBUESC[0m[0003] starting Signal connection                   
2019/07/31 23:17:45 OptionSelector.qml:330: file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/1.3/OptionSelector.qml:330:13: QML ListView: Binding loop detected for property "itemHeight"
2019/07/31 23:17:46 OptionSelector.qml:330: file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/1.3/OptionSelector.qml:330:13: QML ListView: Binding loop detected for property "itemHeight"
ESC[37mDEBUESC[0m[2019/07/31 23:17:46] PUT /v1/directory/tokens 200                 
2019/07/31 23:17:46 OptionSelector.qml:330: file:///usr/lib/arm-linux-gnueabihf/qt5/qml/Ubuntu/Components/1.3/OptionSelector.qml:330:13: QML ListView: Binding loop detected for property "itemHeight"
ESC[37mDEBUESC[0m[2019/07/31 23:17:46] Websocket Connecting to https://textsecure-service.whispersystems.org:443/v1/websocket/ 
ESC[37mDEBUESC[0m[2019/07/31 23:17:46] PUT /v1/messages/+346MYSPANISHFRIENDPHONE 200            
ESC[37mDEBUESC[0m[2019/07/31 23:17:46] SendMessageResponse: {NeedsSync:true Timestamp:1564607866475} 
ESC[37mDEBUESC[0m[2019/07/31 23:17:46] Needs sync. destination: +346MYSPANISHFRIENDPHONE       
ESC[37mDEBUESC[0m[2019/07/31 23:17:46] GET /v2/keys/+336XXXXMYFRENCHPHONE/1 200              
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x391c44]

goroutine 23 [running]:
github.com/nanu-c/textsecure.sendSyncMessage(0x2c84040, 0x2c5e920, 0x28f7ea0, 0x1, 0x1)
        /gopath/src/github.com/nanu-c/textsecure/server.go:618 +0x180
github.com/nanu-c/textsecure.sendMessage(0x295f580, 0x295f580, 0x0, 0x0, 0x0)
        /gopath/src/github.com/nanu-c/textsecure/server.go:590 +0x294
github.com/nanu-c/textsecure.SendMessage(0x2a028d0, 0xc, 0x2aa77c0, 0x50, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/nanu-c/textsecure/textsecure.go:138 +0x68
github.com/nanu-c/textsecure-qml/app/worker.SendMessageLoop(0x2a028d0, 0xc, 0x2aa77c0, 0x50, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /gopath/src/github.com/nanu-c/textsecure-qml/app/worker/message.go:70 +0x224
github.com/nanu-c/textsecure-qml/app/worker.SendMessage(0x2a0d2c0, 0x2abb630)
        /gopath/src/github.com/nanu-c/textsecure-qml/app/worker/message.go:40 +0x6c
created by github.com/nanu-c/textsecure-qml/app/worker.SendUnsentMessages
```

**Comment by Flaburgan** [comment]
I allow myself to up that topic as I am unable to launch the app anymore which is very painful... Is there anything I can do to help?

**Comment by Flaburgan** [comment]
I just asked to my friend and he receives my same message each time I try to launch the signal app.

**Comment by nanu-c** [comment]
actually the fast solution is deleting signal completly

**Comment by Flaburgan** [comment]
Wouldn't that delete my keys and force me to be removed and readded to all my groups again?

**Comment by nanu-c** [comment]
Actually I don't have a quick solution for that problem. Furthermore the whole database system needs a rework because it's to slow, so if i will find the time i will look into signal again i will do more groundwork and if you want to use signal in the next 3 months, then you probably need to re-register. 
I can help you to get you also into development of signal, i would appreciate any help.

**Comment by Flaburgan** [comment]
As I had to reset the keys anyway, and because this app is about security and I am not very comfortable with a not-really-maintained project (not throwing anything at you here, I know very well how the foss world works, thank you for what you're already doing), I went another way and just set up anbox to install the android apk. It went well, I'll test it more in the coming days.

> I can help you to get you also into development of signal, i would appreciate any help.

Sorry but I am a web developer, not knowing enough to help here I guess. I can still report bugs, suggest UX improvements and even donate some money to you, but I don't think I'm going to dev.

**Comment by Apps-Lee** [comment]
Hi nanu-c, Flaburgan reached for help on the UT forum and raised the topic about helping maintain the signal app for UT.
I'm willing to have a look. I tried to install it from sources but I got errors when I run clickable.
I asked for help on UBports forum.
With your help maybe I can get a hold on this project and help maintaining this app.

**Comment by nanu-c** [comment]
Okey, can you reach me at telegram?

**Comment by Apps-Lee** [comment]
I'm on matrix, I thought I found a bridge to your telegram, but seems that it doesn't work this way.
Where can I found your telegram?

**Comment by nanu-c** [comment]
with @nanu_c and then we can switch communication channels

**Comment by nanu-c** [comment]
Please try https://github.com/nanu-c/textsecure-qml/releases

**Comment by Flaburgan** [comment]
I'm sorry but I switched to the official APK using Anbox. If I install this application again, it will changes my keys with all my contacts so I don't want to do that.

**Comment by nanu-c** [comment]
Also a solution for the problem ;)

**Comment by nanu-c** [comment]
Maybe you can try again with v0.7.0 there changed a lot also regarding receiving messages
